---
title: "Get started"
subtitle: "with step-by-steps tutorials"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

*SamsaRaLight* is documented through a series of progressive tutorials that guide users from simple simulations to advanced applications. Although it is advisable to follow the tutorials in the correct order, they are still independent of each other.

1.  [A first minimal case](1-minimal_case.html) - *Compute tree light interception by symmetric crowns in an axis-aligned rectangle plot*

2.  [Understand ray discretization](2-discretisation_directdiffuse.html) - *Discretization of direct and diffuse radiations into rays*

3.  *Represent tree crowns with asymmetric shapes and handle more complex inventory geometries.*

    a. [Non-axis-aligned rectangular stand from GPS data](3a-complex_cases_IRRES.html): Convert geographic coordinates and create an axis-aligned virtual stand.

    b. [Asymmetric crowns in a non-axis-aligned stand](3b-complex_cases_bechefa.html): Use asymmetric crown geometries and fill the surrounding area with virtual trees.

    c. [Non-rectangular inventory zone](3c-complex_cases_cloture.html): Work with complex inventory polygons.


4.  [Understand ray transmission](4-transmission_interception.html) - *Explore transmission models for light propagation through tree crowns, including porous envelope and turbid medium approaches.*

5.  *Estimate the light reaching virtual sensors placed in the stand.*

    a. [Implement virtual sensors](5a-virtual_sensors_concept.html): Introduce the concept and implementation of virtual sensors in the plot.

    b. [Calibrate the LAD parameter](5b-virtual_sensors_lad.html): Use virtual sensor measurements to calibrate the leaf area density parameter

Below is a typical example workflow.

``` r
library(SamsaRaLight)

# Load example inventory
data("data_cloture20")

# Create virtual stand
stand <- create_sl_stand(
  trees_inv = data_cloture20$trees,
  cell_size = 5,
  latitude = 50.03617,
  slope = 0,
  aspect = 0,
  north2x = 90,
  sensors = data_cloture20$sensors,
  core_polygon_df = data_cloture20$core_polygon,
  fill_around = TRUE
)

# Observe input stand
summary(stand)
plot(stand)
plot(stand, top_down = TRUE)

# Get radiation data from PVGIS online database
rad <- get_monthly_radiations(
  latitude = 50.03617, 
  longitude = 5.20634
)

# Run the model
out <- run_sl(
  sl_stand = stand,
  monthly_rad = rad
)

# Plot results
summary(out)
plot(out)
plot(out, show_trees = FALSE)
```
