---
title: "Get started"
subtitle: "with step-by-steps tutorials"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

*SamsaRaLight* is documented through a series of progressive tutorials that guide users from simple simulations to advanced applications. Although it is advisable to follow the tutorials in the correct order, they are still independent of each other.

1. [A first minimal case](1-minimal_case.html) - *Compute tree light interception by symmetric crowns in an axis-aligned rectangle plot*
2. [Understand ray discretization](2-discretisation_directdiffuse.html) - *Discretization of direct and diffuse radiations into rays*
3. [More complex crown shapes and inventories](3-complex_cases.html) - *Represent tree crowns with asymmetric shapes and use non-axis-aligned GPS inventory or non-rectangular inventory zone*
4. [Understand ray transmission](4-transmission_interception.html) - *Transmission models : porous envelope and turbid medium crowns*
5. [Virtual sensors](5-virtual_sensors.html) - *Estimate light arriving towards a virtual sensor*


Below is a typical example workflow.

``` r
library(SamsaRaLight)

# Load example inventory
data("data_cloture20")

# Create virtual stand
stand <- create_sl_stand(
  trees_inv = data_cloture20$trees,
  cell_size = 5,
  latitude = 50.03617,
  slope = 0,
  aspect = 0,
  north2x = 90,
  sensors = data_cloture20$sensors,
  core_polygon_df = data_cloture20$core_polygon,
  fill_around = TRUE
)

# Observe input stand
summary(stand)
plot(stand)
plot(stand, top_down = TRUE)

# Get radiation data from PVGIS online database
rad <- get_monthly_radiations(
  latitude = 50.03617, 
  longitude = 5.20634
)

# Run the model
out <- run_sl(
  sl_stand = stand,
  monthly_rad = rad
)

# Plot results
summary(out)
plot(out)
plot(out, show_trees = FALSE)
```
