---
title: "speed_comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{speed_comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SamsaRaLight)
```

# With 10m cells

```{r speed_10m}
# microbenchmark::microbenchmark(
#   "r" = SamsaRaLight::sl_run(
#     trees, monthly_rad,
#     latitude = latitude, slope = slope, 
#     aspect = aspect, north_to_x_cw = north_to_x_cw,
#     cell_size = 10, n_cells = 10,
#     use_rcpp = FALSE
#   ),
#   "rcpp" = SamsaRaLight::sl_run(
#     trees, monthly_rad,
#     latitude = latitude, slope = slope, 
#     aspect = aspect, north_to_x_cw = north_to_x_cw,
#     cell_size = 10, n_cells = 10,
#     use_rcpp = TRUE
#   ),
#   times = 10
# )
```

# With 5m cells

```{r speed_5m}
# microbenchmark::microbenchmark(
#   "r" = SamsaRaLight::sl_run(
#     trees, monthly_rad,
#     latitude = latitude, slope = slope,
#     aspect = aspect, north_to_x_cw = north_to_x_cw,
#     cell_size = 5, n_cells = 20,
#     use_rcpp = FALSE
#   ),
#   "rcpp" = SamsaRaLight::sl_run(
#     trees, monthly_rad,
#     latitude = latitude, slope = slope,
#     aspect = aspect, north_to_x_cw = north_to_x_cw,
#     cell_size = 5, n_cells = 20,
#     use_rcpp = TRUE
#   ),
#   times = 10
# )
```