# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sl_run_rcpp <- function(trees, sensors, sensors_only, rays, e_above_m2, slope, north_to_x_cw, aspect, cell_size, n_cells_x, n_cells_y, use_torus, turbid_medium, trunk_interception) {
    .Call(`_SamsaRaLight_sl_run_rcpp`, trees, sensors, sensors_only, rays, e_above_m2, slope, north_to_x_cw, aspect, cell_size, n_cells_x, n_cells_y, use_torus, turbid_medium, trunk_interception)
}

